import "../tools/search-products-tool.js";

import { ClaudeService } from "./claude-service.js";
import { getBedrockTools } from "../tools/bedrock-tools.js";
import { getTool } from "../tools/tool-registry.js";


/**
 * Metadata describing the resulting dataset.
 *
 * title and description are generated by the agent from
 * the user's intent.
 *
 * resultCount is generated deterministically after the
 * selected capability has executed.
 */
export interface ResultMetadata {
    title: string;
    qualifiers: string[];
    resultCount: number;
}


/**
 * Standard Resulting Data Store returned by the AEA
 * agent orchestration layer.
 *
 * The view layer receives:
 *
 *   metadata - semantic description of the result
 *   dataset  - records produced by the selected capability
 *
 * The view layer does not need to know which tool,
 * repository, query, or infrastructure component produced
 * the data.
 */
export interface AgentResult {
    metadata: ResultMetadata;
    dataset: unknown[];
}


/**
 * Agent-facing execution contract.
 *
 * Claude produces this structure as the input to the
 * capability it selects.
 *
 * request:
 *   Capability-specific execution criteria.
 *
 * metadata:
 *   Semantic description of the result expected from
 *   executing that request.
 */
interface AgentToolInput {
    request: unknown;

    metadata: {
        title: string;
        qualifiers: string[];
    };
}


/**
 * AgentService
 *
 * Coordinates execution of a natural-language user intent
 * through the AEA agentic pipeline.
 *
 *   User Intent
 *       ↓
 *   Claude establishes Agentic Execution Contract
 *       ├── capability/tool
 *       ├── request criteria
 *       └── result metadata
 *       ↓
 *   Tool Registry resolves capability
 *       ↓
 *   Capability executes request
 *       ↓
 *   Capability result is normalized using its
 *   ResultDefinition
 *       ↓
 *   AEA Resulting Data Store
 *       ↓
 *   View Layer
 *
 * ClaudeService interprets intent but does not execute
 * application capabilities.
 *
 * AgentService owns deterministic execution and result
 * normalization.
 */
export class AgentService {

    private readonly claude: ClaudeService;


    constructor() {
        this.claude = new ClaudeService();
    }


    /**
     * Process a natural-language user intent.
     *
     * Example:
     *
     *   "Show me everything Lily has to offer."
     *
     * Claude may establish:
     *
     *   toolName: "searchProducts"
     *
     *   toolInput: {
     *     request: {
     *       returnAllProducts: true
     *     },
     *
     *     metadata: {
     *       title: "Lily Product Catalog",
     *       description:
     *         "All products currently available from Lily."
     *     }
     *   }
     *
     * AgentService executes only the request portion.
     */
    async processIntent(
        prompt: string
    ): Promise<AgentResult> {

        /*
         * Step 1:
         * Ask Claude to translate the user's natural-language
         * intent into an Agentic Execution Contract.
         */
        const decision =
            await this.claude.invokeWithTools(
                prompt,
                getBedrockTools()
            );


        /*
         * A data-producing intent currently requires Claude
         * to select a registered capability.
         */
        if (!decision.toolName) {
            throw new Error(
                "Agent did not select a tool."
            );
        }


        /*
         * Step 2:
         * Resolve the capability through the application-owned
         * tool registry.
         *
         * Claude selects capabilities but never directly
         * executes application code.
         */
        const tool =
            getTool(decision.toolName);

        if (!tool) {
            throw new Error(
                `Agent requested unknown tool: ${decision.toolName}`
            );
        }


        /*
         * Step 3:
         * Interpret Claude's tool input as the common AEA
         * Agentic Execution Contract.
         */
        const agentInput =
            decision.toolInput as AgentToolInput;


        /*
         * Validate the common portions of the execution
         * contract before executing application code.
         */
        if (
            !agentInput ||
            !agentInput.request ||
            !agentInput.metadata ||
            !agentInput.metadata.title ||
            !Array.isArray(agentInput.metadata.qualifiers)
        ) {
            throw new Error(
                "Agent returned an invalid execution contract."
            );
        }


        /*
         * Step 4:
         * Execute only the capability-specific request.
         *
         * Agent-generated result metadata is deliberately
         * NOT passed into the capability or repository.
         */
        const result =
            await tool.execute(
                agentInput.request
            );


        /*
         * Step 5:
         * Normalize the capability-specific result using
         * the ResultDefinition registered with the tool.
         *
         * This keeps AgentService independent of specific
         * result names such as "products", "orders", etc.
         */
        const resultObject =
            result as Record<string, unknown>;

        const datasetValue =
            resultObject[
            tool.resultDefinition.datasetField
            ];


        if (!Array.isArray(datasetValue)) {
            throw new Error(
                `Tool ${decision.toolName} did not return expected dataset field: ` +
                tool.resultDefinition.datasetField
            );
        }


        /*
         * Step 6:
         * Construct the AEA Resulting Data Store.
         *
         * Semantic metadata is agent-generated.
         *
         * resultCount is deterministic because it is derived
         * from the actual executed dataset.
         */
        return {
            metadata: {
                title:
                    agentInput.metadata.title,

                qualifiers:
                    agentInput.metadata.qualifiers,

                resultCount:
                    datasetValue.length
            },

            dataset:
                datasetValue
        };
    }
}