import type { ProductSearchRequest } from "../models/product-search-request.js";
import type { ToolDefinition } from "./tool-registry.js";
import { appendTool } from "./tool-registry.js";
import { CatalogRepository } from "../repositories/catalog-repository.js";


type ProductSearchResult = {
  function: string;
  request: ProductSearchRequest;
  products: unknown[];
};


const catalogRepository =
  new CatalogRepository();


const searchProductsTool: ToolDefinition<
  ProductSearchRequest,
  ProductSearchResult
> = {

  name: "searchProducts",

  description:
    "Search Lily's product inventory. Use this function when the customer wants to view products Lily offers.",


  /**
   * Functional request contract.
   *
   * Defines the structured criteria required by the
   * searchProducts capability.
   */
  inputSchema: {
    type: "object",

    properties: {
      returnAllProducts: {
        type: "boolean",

        description:
          "Set to true when the customer wants to see everything Lily has to offer."
      }
    },

    required: [
      "returnAllProducts"
    ]
  },


  /**
   * Result contract.
   *
   * Defines how the capability result maps into the
   * AEA Resulting Data Store.
   *
   * products identifies the collection returned by this
   * capability that should become the view-layer dataset.
   *
   * Metadata values are generated by the agent based on
   * the user's intent.
   */
  resultDefinition: {

    datasetField: "products",

    metadataSchema: {

      title: {
        type: "string",

        description:
          "A short, meaningful and abstract heading for the resulting product view. Do not enumerate individual search criteria or filters in the title."
      },

      qualifiers: {
        type: "array",

        items: {
          type: "string"
        },

        description:
          "A list of concise human-readable qualifiers that affected the product search. Include actual filters or constraints inferred from the user's request. Do not include generic statements. Return an empty array when the request contains no filtering qualifiers."
      }
    }
  },


  /**
   * Execute product search.
   *
   * Execution remains deterministic. Agent-generated
   * metadata is not passed into the repository.
   */
  execute: async (input) => {

    console.log("Executing searchProducts");
    console.log(
      "returnAllProducts:",
      input.returnAllProducts
    );

    const products =
      await catalogRepository.searchProducts(
        input
      );

    return {
      function: "searchProducts",
      request: input,
      products
    };
  }
};


appendTool(searchProductsTool);