/**
 * Describes metadata that the agent should generate for the
 * resulting data store.
 *
 * The schema defines the semantic information expected by the
 * view layer. Actual values are generated by the agent from
 * the user's intent.
 */
export type ResultMetadataDefinition = {
  title: {
    type: "string";
    description: string;
  };

  qualifiers: {
    type: "array";
    items: {
      type: "string";
    };
    description: string;
  };
};

/**
 * Describes how the result returned by a capability should be
 * normalized into the AEA Resulting Data Store.
 *
 * datasetField identifies the collection within the tool result
 * that represents the records to be rendered by the view layer.
 */
export type ResultDefinition = {
  datasetField: string;

  metadataSchema: ResultMetadataDefinition;
};

/**
 * Standard definition for an AEA agentic capability.
 *
 * inputSchema:
 *   Defines the structured request understood by the capability.
 *
 * resultDefinition:
 *   Defines how the capability result participates in the
 *   Resulting Data Store contract.
 *
 * execute:
 *   Performs deterministic server-side execution.
 */
export type ToolDefinition<TInput = unknown, TResult = unknown> = {
  name: string;

  description: string;

  inputSchema: object;

  resultDefinition: ResultDefinition;

  execute: (input: TInput, context?: { requestId: string }) => Promise<TResult>;
};

const toolRegistry: Record<string, ToolDefinition<any, any>> = {};

export function appendTool(tool: ToolDefinition<any, any>): void {
  if (toolRegistry[tool.name]) {
    throw new Error(`Tool already exists: ${tool.name}`);
  }

  toolRegistry[tool.name] = tool;
}

export function getTool(name: string) {
  return toolRegistry[name];
}

export function getAllTools() {
  return Object.values(toolRegistry);
}
